
%LET PATH = D:\workshop\lumap;
%LET ConfigDir=d:/sas/config/Lev1;
%let encoding=utf8;
%let projection=luref;
 
/*%LET PATH = /workshop/lumap/sascode/;*/
/*%LET ConfigDir = /sas/config/Lev1;*/
/*%include "&PATH.Change Length in Map Data.sas";*/
/*Final Script voor Municipality*/
/*Parameters*/

%let REGION_LABEL=Luxembourg Municipality;
%let REGION_PREFIX=ZL;
%let REGION_ISO=934;
%let PROVINCE_LABEL=Custom Lux Municipality;
%let PROVINCE_DATASET=MAPSCSTM.CUSTOM_MUNLU1;

libname mapscstm "&path/sasdata"; 
proc mapimport datafile="&path\addresses\addresses.shp"  out=mapscstm.addresses contents ; 
run; 




GOPTIONS ACCESSIBLE;
/* create libraries */
libname valib "&configdir/SASApp/Data/valib";
libname MAPSCSTM "&path/sasdata";


/* import SHAPE file to SAS dataset */
PROC MAPIMPORT 	DATAFILE="&path/limadmin/LIMADM_COMMUNES.shp" contents
				OUT=MAPSCSTM.MunicipalityLUREF;
				ID LAU2;
RUN;


/* add DENSITY variable */
PROC GREDUCE DATA=MAPSCSTM.MunicipalityLUREF OUT=MAPSCSTM.MunicipalityLUREF;
	ID LAU2;
RUN;

data MAPSCSTM.MunicipalityLUREF; 
length lau2 $4; 
set MAPSCSTM.MunicipalityLUREF; 
run; 


/* create Custom Regions dataset */
data &PROVINCE_DATASET.LUREF;
 SET MAPSCSTM.MunicipalityLUREF;
 length ID $ 15 IDNAME $55; 
 ID = compress("&REGION_PREFIX.-" || put(LAU2,$4.));
 IDNAME = Propcase(COMMUNE);
 LONG = X;
 LAT = Y;
 ISO = "&REGION_ISO.";
 RESOLUTION = 1;
 LAKE = 0;
 ISOALPHA2 = "&REGION_PREFIX.";
 AdminType = "regions";
 WHERE DENSITY <= 2;
 keep ID SEGMENT IDNAME LONG LAT X Y ISO DENSITY RESOLUTION LAKE ISOALPHA2 AdminType;
run;



/*create test table*/

GOPTIONS ACCESSIBLE;
proc sql;
   create table &PROVINCE_DATASET.LUREF_TEST as
   select distinct 
       ID as ID,
       IDNAME as NAME
   from &PROVINCE_DATASET.;
   create table &PROVINCE_DATASET._TEST as
   select *,
       round(ranuni(1) * 10000) as population,
       round(ranuni(1) * 100000) as avg_income format=dollar20.0
   from &PROVINCE_DATASET._TEST
   group by ID, NAME
   order by ID, NAME
;quit;run;

/*select Avenue Gaston Diderich nr 54*/
proc sql; 
create table work.query_for_addresses_0002 as 
select * from mapscstm.addresses t1
WHERE t1.rue = 'Avenue Gaston Diderich' AND t1.numero = '54';
quit; 

/*As of SAS94M5 you can use the new proc sgmap to produce maps with different layers of information*/
/*Choromap creates a map with regions*/
/*Scatter adds a layer of text where i annotate the information of one street to the map*/
proc SGMAP mapdata=mapscstm.custom_munlu1luref respDATA=mapscstm.custom_munlu1_poparea 
	plotdata=WORK.QUERY_FOR_ADDRESSES_0002;
	
	CHOROMAP population /mapid=id id=id ; 
	scatter   x=x y=y / markerattrs=(symbol=diamond color=red) datalabel=rue;
		
	;
RUN;
QUIT;

TITLE;FOOTNOTE;

GOPTIONS CBACK=;

/* -------------------------------------------------------------------
   Code generated by SAS Task

   Generated on: Friday, October 30, 2020 at 9:54:32 AM
   By task: Map Chart

   Map Data: Local:MAPSCSTM.MUNICIPALITYLUREF   Response Data: Local:MAPSCSTM.MUNICIPALITYLUREF_POPAREA   Server: Local
   ------------------------------------------------------------------- */
/*Annotate dataset example based on addresses:*/
/*Function symbol plots a star on top of the location of Av Biderich*/
/*Function label adds text to a position on the map*/
data work.anno;
length function style color $ 8 position $ 1
          text $ 30;
   retain xsys ysys "2" hsys "3"
          when "a";
   set work.query_for_addresses_0002; 
   function="symbol"; style="marker"; text="V"; color="red"; size=5;
      output;
   function="label"; style=""; text=rue; color="green";
      size=2; position="6"; output;
run;


GOPTIONS CBACK= ;

TITLE;FOOTNOTE;
LEGEND1
	FRAME
	LABEL=(FONT='Microsoft Sans Serif' HEIGHT=12pt JUSTIFY=LEFT )
	;

TITLE1 "Population par Commune Luxembourg";

FOOTNOTE1 "Generated by SAS (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%QSYSFUNC(TIME(), NLTIMAP25.))";

proc format ;
value poprange 
				low-1000='0-1000'
				1000-2000='1000-2000'
				2000-5000='2000-5000'
				5000-7500='5000-7500'
				7500-10000='7500-10000'
				10000-15000='10000-15000'
				15000-40000='15000-40000'
				40000-high='40000+' ;
				
run; 
PROC GMAP GOUT=MAPCHART DATA=MAPSCSTM.MUNICIPALITYLUREF_POPAREA MAP=MAPSCSTM.MUNICIPALITYLUREF ALL;
	ID lau2;
	format population poprange.;
	CHORO POPULATION /levels=all
		WOUTLINE=1
		LEGEND=LEGEND1 anno=anno
		;
RUN;
QUIT;

TITLE;FOOTNOTE;

GOPTIONS CBACK=;
